-- USERS TABLE

CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL
);


-- FOOD LOGS (ANALYSIS)

CREATE TABLE IF NOT EXISTS food_logs (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
food_name TEXT,
calories INTEGER,
category TEXT,
health_score INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ORDERS TABLE

CREATE TABLE IF NOT EXISTS orders (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER,
food_name TEXT,
price INTEGER,
category TEXT,
status TEXT,
order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);